/**
 * CET-4 level common words with their typical/common meanings.
 * When a word appears in the user's notes with a meaning significantly different
 * from these common meanings, it is flagged as 熟词僻义 (isCommonWord: true).
 *
 * Format: word -> array of common meaning keywords in Chinese
 */
export const COMMON_WORDS: Record<string, string[]> = {
  // A
  "abandon": ["放弃", "抛弃"],
  "ability": ["能力"],
  "able": ["能够"],
  "about": ["关于", "大约"],
  "above": ["上面"],
  "accept": ["接受"],
  "according": ["根据"],
  "account": ["账户", "账号"],
  "achieve": ["实现", "达到"],
  "across": ["穿过"],
  "act": ["行动", "行为"],
  "action": ["行动"],
  "active": ["积极的", "活跃的"],
  "activity": ["活动"],
  "add": ["添加", "加"],
  "address": ["地址"],
  "age": ["年龄"],
  "ago": ["以前"],
  "agree": ["同意"],
  "air": ["空气"],
  "all": ["所有"],
  "allow": ["允许"],
  "almost": ["几乎"],
  "along": ["沿着"],
  "already": ["已经"],
  "also": ["也"],
  "always": ["总是"],
  "among": ["在…之中"],
  "amount": ["数量"],
  "animal": ["动物"],
  "another": ["另一个"],
  "answer": ["回答", "答案"],
  "appear": ["出现", "似乎"],
  "apply": ["申请", "应用"],
  "approach": ["方法", "接近"],
  "area": ["地区", "区域"],
  "arm": ["手臂"],
  "around": ["周围"],
  "art": ["艺术"],
  "article": ["文章"],
  "atmosphere": ["气氛", "氛围"],
  "attack": ["攻击"],
  "attention": ["注意"],
  "available": ["可用的"],
  // B
  "back": ["背部", "回来"],
  "bad": ["坏的"],
  "bank": ["银行"],
  "bar": ["酒吧", "条"],
  "base": ["基础"],
  "bear": ["熊", "忍受"],
  "beat": ["打", "击败"],
  "become": ["变成"],
  "bed": ["床"],
  "before": ["在…之前"],
  "begin": ["开始"],
  "behind": ["在…后面"],
  "believe": ["相信"],
  "best": ["最好的"],
  "better": ["更好的"],
  "between": ["在…之间"],
  "big": ["大的"],
  "bill": ["账单"],
  "bit": ["一点"],
  "black": ["黑色的"],
  "blood": ["血"],
  "blue": ["蓝色的"],
  "board": ["板", "董事会"],
  "body": ["身体"],
  "book": ["书"],
  "born": ["出生"],
  "both": ["两者"],
  "break": ["打破", "休息"],
  "bring": ["带来"],
  "broad": ["宽的", "广泛的"],
  "brook": ["小溪"],
  "brother": ["兄弟"],
  "build": ["建造"],
  "business": ["商业", "生意"],
  "buy": ["买"],
  // C
  "call": ["打电话", "叫"],
  "can": ["能够", "罐头"],
  "capital": ["首都", "资本"],
  "card": ["卡片"],
  "care": ["关心", "照顾"],
  "carry": ["携带"],
  "case": ["情况", "案例"],
  "catch": ["抓住"],
  "cause": ["原因", "导致"],
  "center": ["中心"],
  "certain": ["确定的", "某些"],
  "chance": ["机会"],
  "change": ["改变"],
  "character": ["性格", "角色", "人物"],
  "charge": ["收费", "充电"],
  "check": ["检查"],
  "child": ["孩子"],
  "choice": ["选择"],
  "church": ["教堂"],
  "city": ["城市"],
  "claim": ["声称"],
  "class": ["班级", "课"],
  "clear": ["清楚的"],
  "climate": ["气候"],
  "close": ["关闭", "近的"],
  "coast": ["海岸"],
  "cold": ["冷的"],
  "color": ["颜色"],
  "come": ["来"],
  "common": ["共同的", "常见的"],
  "community": ["社区"],
  "company": ["公司"],
  "complete": ["完成", "完整的"],
  "condition": ["条件", "状况"],
  "consider": ["考虑"],
  "contain": ["包含"],
  "continue": ["继续"],
  "control": ["控制"],
  "core": ["核心"],
  "cost": ["花费", "成本"],
  "could": ["能够"],
  "country": ["国家"],
  "course": ["课程"],
  "cover": ["覆盖", "封面"],
  "create": ["创造"],
  "cross": ["穿越", "十字"],
  "culture": ["文化"],
  "current": ["当前的", "目前的"],
  "cut": ["切", "剪"],
  // D
  "dark": ["黑暗的"],
  "data": ["数据"],
  "daughter": ["女儿"],
  "day": ["天", "日"],
  "dead": ["死的"],
  "deal": ["处理", "交易"],
  "death": ["死亡"],
  "decide": ["决定"],
  "deep": ["深的"],
  "degree": ["学位", "程度", "度"],
  "demand": ["需求", "要求"],
  "develop": ["发展"],
  "die": ["死"],
  "difference": ["区别"],
  "different": ["不同的"],
  "difficult": ["困难的"],
  "direction": ["方向"],
  "discover": ["发现"],
  "discuss": ["讨论"],
  "do": ["做"],
  "doctor": ["医生"],
  "door": ["门"],
  "down": ["下"],
  "draw": ["画"],
  "dream": ["梦"],
  "drive": ["开车", "驾驶"],
  "drop": ["掉落", "下降"],
  "during": ["在…期间"],
  // E
  "each": ["每个"],
  "early": ["早的"],
  "east": ["东方"],
  "easy": ["容易的"],
  "eat": ["吃"],
  "economy": ["经济"],
  "education": ["教育"],
  "effect": ["效果", "影响"],
  "effort": ["努力"],
  "eight": ["八"],
  "either": ["任一"],
  "end": ["结束", "末端"],
  "energy": ["能量", "精力"],
  "enjoy": ["享受"],
  "enough": ["足够"],
  "enter": ["进入"],
  "environment": ["环境"],
  "even": ["甚至", "偶数的"],
  "evening": ["晚上"],
  "event": ["事件"],
  "ever": ["曾经"],
  "every": ["每个"],
  "evidence": ["证据"],
  "example": ["例子"],
  "exist": ["存在"],
  "expect": ["期望"],
  "experience": ["经验", "经历"],
  "explain": ["解释"],
  "eye": ["眼睛"],
  // F
  "face": ["脸", "面对"],
  "fact": ["事实"],
  "fall": ["落下", "秋天"],
  "family": ["家庭"],
  "far": ["远的"],
  "fast": ["快的"],
  "father": ["父亲"],
  "fear": ["害怕", "恐惧"],
  "feel": ["感觉"],
  "few": ["少数"],
  "field": ["领域", "田地"],
  "fight": ["战斗", "打架"],
  "figure": ["数字", "人物", "身材"],
  "fill": ["填满"],
  "final": ["最终的"],
  "find": ["找到"],
  "fine": ["好的", "罚款"],
  "fire": ["火"],
  "first": ["第一"],
  "fish": ["鱼"],
  "five": ["五"],
  "flat": ["平的", "平坦的"],
  "floor": ["地板", "楼层"],
  "fly": ["飞"],
  "follow": ["跟随"],
  "food": ["食物"],
  "foot": ["脚"],
  "for": ["为了"],
  "force": ["力量", "强迫"],
  "foreign": ["外国的"],
  "form": ["形式", "表格"],
  "forward": ["向前"],
  "four": ["四"],
  "free": ["自由的", "免费的"],
  "friend": ["朋友"],
  "from": ["从"],
  "front": ["前面"],
  "full": ["满的"],
  "fund": ["基金"],
  "future": ["未来"],
  // G
  "game": ["游戏", "比赛"],
  "garden": ["花园"],
  "general": ["一般的", "总的"],
  "get": ["得到"],
  "girl": ["女孩"],
  "give": ["给"],
  "glass": ["玻璃", "杯子"],
  "globe": ["地球仪", "球体"],
  "go": ["去"],
  "goal": ["目标"],
  "gold": ["金", "黄金"],
  "good": ["好的"],
  "government": ["政府"],
  "great": ["伟大的", "很棒的"],
  "green": ["绿色的"],
  "ground": ["地面"],
  "group": ["团体", "组"],
  "grow": ["生长", "成长"],
  "growth": ["增长"],
  "gun": ["枪"],
  // H
  "hair": ["头发"],
  "half": ["一半"],
  "hand": ["手"],
  "happen": ["发生"],
  "happy": ["高兴的"],
  "hard": ["硬的", "困难的", "努力地"],
  "have": ["有"],
  "he": ["他"],
  "head": ["头"],
  "health": ["健康"],
  "hear": ["听"],
  "heart": ["心"],
  "heat": ["热"],
  "heavy": ["重的"],
  "help": ["帮助"],
  "here": ["这里"],
  "high": ["高的"],
  "history": ["历史"],
  "hold": ["持有", "举行"],
  "home": ["家"],
  "hope": ["希望"],
  "horizon": ["地平线"],
  "hot": ["热的"],
  "hotel": ["酒店"],
  "hour": ["小时"],
  "house": ["房子"],
  "how": ["怎样"],
  "however": ["然而"],
  "human": ["人类的"],
  "hundred": ["百"],
  // I-J
  "idea": ["主意", "想法"],
  "image": ["图像", "形象"],
  "important": ["重要的"],
  "include": ["包括"],
  "increase": ["增加"],
  "indeed": ["确实"],
  "indicate": ["表明"],
  "industry": ["工业"],
  "information": ["信息"],
  "inside": ["里面"],
  "interest": ["兴趣", "利息"],
  "into": ["进入"],
  "issue": ["问题", "发行"],
  "it": ["它"],
  "item": ["项目", "物品"],
  "job": ["工作"],
  "join": ["加入"],
  "just": ["刚刚", "只是"],
  // K-L
  "keep": ["保持"],
  "key": ["钥匙", "关键"],
  "kid": ["孩子"],
  "kill": ["杀"],
  "kind": ["种类", "友好的"],
  "know": ["知道"],
  "land": ["土地", "着陆"],
  "language": ["语言"],
  "large": ["大的"],
  "last": ["最后的", "持续"],
  "late": ["迟的"],
  "later": ["后来"],
  "law": ["法律"],
  "lay": ["放置"],
  "lead": ["领导", "铅"],
  "learn": ["学习"],
  "leave": ["离开"],
  "left": ["左边的"],
  "less": ["更少"],
  "let": ["让"],
  "letter": ["信", "字母"],
  "level": ["水平"],
  "lie": ["说谎", "躺"],
  "life": ["生活", "生命"],
  "light": ["光", "轻的"],
  "like": ["喜欢", "像"],
  "line": ["线", "线路"],
  "list": ["列表"],
  "listen": ["听"],
  "little": ["小的"],
  "live": ["住", "活"],
  "long": ["长的"],
  "look": ["看"],
  "lose": ["失去"],
  "loss": ["损失"],
  "lot": ["很多"],
  "love": ["爱"],
  "low": ["低的"],
  // M
  "machine": ["机器"],
  "main": ["主要的"],
  "major": ["主要的", "专业"],
  "make": ["做", "制造"],
  "man": ["男人"],
  "manage": ["管理"],
  "many": ["许多"],
  "market": ["市场"],
  "material": ["材料"],
  "matter": ["事情", "物质"],
  "may": ["可能"],
  "mean": ["意思是", "意味着"],
  "measure": ["测量", "措施"],
  "meet": ["遇见"],
  "member": ["成员"],
  "memory": ["记忆"],
  "mention": ["提到"],
  "method": ["方法"],
  "middle": ["中间"],
  "might": ["可能"],
  "mind": ["介意", "思想"],
  "minute": ["分钟"],
  "miss": ["想念", "错过"],
  "model": ["模型"],
  "modern": ["现代的"],
  "moment": ["时刻"],
  "money": ["钱"],
  "month": ["月"],
  "more": ["更多"],
  "morning": ["早上"],
  "most": ["最多"],
  "mother": ["母亲"],
  "move": ["移动"],
  "much": ["很多"],
  "music": ["音乐"],
  "must": ["必须"],
  // N
  "name": ["名字"],
  "narrow": ["狭窄的"],
  "nation": ["国家"],
  "natural": ["自然的"],
  "nature": ["自然"],
  "near": ["近的"],
  "necessary": ["必要的"],
  "need": ["需要"],
  "never": ["从不"],
  "new": ["新的"],
  "news": ["新闻"],
  "next": ["下一个"],
  "night": ["夜晚"],
  "no": ["不"],
  "none": ["没有一个"],
  "nor": ["也不"],
  "north": ["北方"],
  "not": ["不"],
  "note": ["笔记", "注意"],
  "nothing": ["什么都没有"],
  "notice": ["注意到"],
  "now": ["现在"],
  "number": ["数字", "号码"],
  // O
  "ocean": ["海洋"],
  "off": ["关闭"],
  "offer": ["提供"],
  "office": ["办公室"],
  "officer": ["军官", "官员"],
  "often": ["经常"],
  "oil": ["油"],
  "old": ["旧的", "老的"],
  "on": ["在…上"],
  "once": ["一次"],
  "one": ["一"],
  "only": ["只有"],
  "open": ["打开"],
  "operation": ["手术", "操作"],
  "opportunity": ["机会"],
  "option": ["选项"],
  "or": ["或者"],
  "order": ["命令", "订单", "顺序"],
  "other": ["其他的"],
  "out": ["出去"],
  "outside": ["外面"],
  "over": ["在…上方", "超过"],
  "own": ["自己的", "拥有"],
  // P
  "page": ["页"],
  "paper": ["纸", "论文"],
  "part": ["部分"],
  "particular": ["特别的"],
  "party": ["派对", "政党"],
  "pass": ["通过", "经过"],
  "past": ["过去"],
  "patient": ["病人", "耐心的"],
  "pay": ["支付"],
  "peace": ["和平"],
  "people": ["人们"],
  "per": ["每"],
  "perform": ["表演", "执行"],
  "period": ["时期"],
  "person": ["人"],
  "phone": ["电话"],
  "physical": ["身体的", "物理的"],
  "pick": ["挑选"],
  "picture": ["图片"],
  "piece": ["片", "块"],
  "place": ["地方"],
  "plain": ["简单的", "朴素的", "明白的"],
  "plan": ["计划"],
  "plant": ["植物", "工厂"],
  "play": ["玩", "演奏"],
  "player": ["玩家", "选手"],
  "please": ["请"],
  "point": ["点", "指向"],
  "police": ["警察"],
  "policy": ["政策"],
  "political": ["政治的"],
  "poor": ["贫穷的"],
  "popular": ["受欢迎的"],
  "population": ["人口"],
  "position": ["位置", "职位"],
  "positive": ["积极的"],
  "possible": ["可能的"],
  "power": ["力量", "权力"],
  "practice": ["练习", "实践"],
  "present": ["现在的", "礼物", "出席"],
  "president": ["总统"],
  "pressure": ["压力"],
  "pretty": ["漂亮的"],
  "prevent": ["防止"],
  "price": ["价格"],
  "private": ["私人的"],
  "probably": ["可能"],
  "problem": ["问题"],
  "process": ["过程", "处理"],
  "produce": ["生产"],
  "product": ["产品"],
  "program": ["程序", "项目"],
  "project": ["项目"],
  "property": ["财产", "属性"],
  "protect": ["保护"],
  "prove": ["证明"],
  "provide": ["提供"],
  "public": ["公共的"],
  "pull": ["拉"],
  "purpose": ["目的"],
  "push": ["推"],
  "put": ["放"],
  // Q-R
  "quality": ["质量"],
  "question": ["问题"],
  "quite": ["相当"],
  "race": ["比赛", "种族"],
  "raise": ["提高", "举起"],
  "range": ["范围"],
  "rate": ["速率", "比率"],
  "reach": ["达到", "到达"],
  "read": ["读"],
  "ready": ["准备好的"],
  "real": ["真实的"],
  "reality": ["现实"],
  "realize": ["意识到"],
  "really": ["真的"],
  "reason": ["原因"],
  "receive": ["收到"],
  "recent": ["最近的"],
  "record": ["记录"],
  "red": ["红色的"],
  "reduce": ["减少"],
  "region": ["地区"],
  "relate": ["联系"],
  "remain": ["保持", "剩余"],
  "remember": ["记住"],
  "remove": ["移除"],
  "report": ["报告"],
  "represent": ["代表"],
  "require": ["需要"],
  "research": ["研究"],
  "resource": ["资源"],
  "response": ["回应"],
  "rest": ["休息"],
  "result": ["结果"],
  "return": ["返回"],
  "right": ["右边的", "正确的", "权利"],
  "rise": ["上升"],
  "risk": ["风险"],
  "road": ["路"],
  "rock": ["岩石", "摇滚"],
  "role": ["角色"],
  "room": ["房间"],
  "rule": ["规则"],
  "run": ["跑"],
  // S
  "safe": ["安全的"],
  "same": ["相同的"],
  "save": ["保存", "拯救"],
  "say": ["说"],
  "school": ["学校"],
  "science": ["科学"],
  "season": ["季节"],
  "second": ["第二", "秒"],
  "section": ["部分"],
  "see": ["看见"],
  "seem": ["似乎"],
  "send": ["发送"],
  "sense": ["感觉", "意义"],
  "serious": ["严重的", "认真的"],
  "serve": ["服务"],
  "service": ["服务"],
  "set": ["设置", "放置"],
  "seven": ["七"],
  "several": ["几个"],
  "shallow": ["浅的"],
  "share": ["分享"],
  "she": ["她"],
  "short": ["短的"],
  "should": ["应该"],
  "show": ["展示"],
  "side": ["边"],
  "sign": ["标志", "签名"],
  "significant": ["重要的", "显著的"],
  "similar": ["相似的"],
  "simple": ["简单的"],
  "since": ["自从"],
  "single": ["单个的"],
  "sit": ["坐"],
  "site": ["地点", "网站"],
  "situation": ["情况"],
  "six": ["六"],
  "size": ["大小"],
  "skill": ["技能"],
  "small": ["小的"],
  "social": ["社会的"],
  "society": ["社会"],
  "soldier": ["士兵"],
  "some": ["一些"],
  "son": ["儿子"],
  "song": ["歌"],
  "soon": ["很快"],
  "sort": ["种类", "排序"],
  "sound": ["声音"],
  "source": ["来源"],
  "south": ["南方"],
  "space": ["空间", "太空"],
  "speak": ["说话"],
  "special": ["特别的"],
  "spring": ["春天", "弹簧"],
  "stage": ["阶段", "舞台"],
  "stand": ["站"],
  "standard": ["标准"],
  "star": ["星星", "明星"],
  "start": ["开始"],
  "state": ["状态", "国家", "州"],
  "stay": ["停留"],
  "steep": ["陡峭的"],
  "step": ["步骤", "脚步"],
  "still": ["仍然"],
  "stop": ["停止"],
  "story": ["故事"],
  "street": ["街道"],
  "strong": ["强壮的"],
  "structure": ["结构"],
  "student": ["学生"],
  "study": ["学习", "研究"],
  "subject": ["科目", "主题"],
  "success": ["成功"],
  "such": ["这样的"],
  "suddenly": ["突然"],
  "suggest": ["建议"],
  "support": ["支持"],
  "sure": ["确定的"],
  "system": ["系统"],
  // T
  "table": ["桌子", "表格"],
  "take": ["拿", "带"],
  "talk": ["谈话"],
  "tax": ["税"],
  "teach": ["教"],
  "teacher": ["老师"],
  "team": ["队伍"],
  "tell": ["告诉"],
  "ten": ["十"],
  "term": ["学期", "术语"],
  "test": ["测试"],
  "than": ["比"],
  "thank": ["感谢"],
  "that": ["那个"],
  "the": ["这个"],
  "their": ["他们的"],
  "them": ["他们"],
  "then": ["然后"],
  "there": ["那里"],
  "these": ["这些"],
  "they": ["他们"],
  "thing": ["事情"],
  "think": ["想"],
  "third": ["第三"],
  "this": ["这个"],
  "those": ["那些"],
  "though": ["虽然"],
  "thought": ["想法"],
  "three": ["三"],
  "through": ["通过"],
  "throw": ["扔"],
  "thus": ["因此"],
  "tide": ["潮汐"],
  "time": ["时间"],
  "to": ["到"],
  "today": ["今天"],
  "together": ["一起"],
  "too": ["也", "太"],
  "top": ["顶部"],
  "total": ["总共"],
  "town": ["镇"],
  "trade": ["贸易"],
  "travel": ["旅行"],
  "treat": ["对待"],
  "tree": ["树"],
  "trial": ["审判", "试验"],
  "trip": ["旅行"],
  "trouble": ["麻烦"],
  "true": ["真的"],
  "truth": ["真相"],
  "try": ["尝试"],
  "turn": ["转"],
  "two": ["二"],
  "type": ["类型"],
  // U-V
  "under": ["在…下面"],
  "understand": ["理解"],
  "unit": ["单位"],
  "until": ["直到"],
  "up": ["向上"],
  "upon": ["在…上"],
  "use": ["使用"],
  "usually": ["通常"],
  "value": ["价值"],
  "very": ["非常"],
  "view": ["观点", "景色"],
  "visit": ["参观", "访问"],
  "voice": ["声音"],
  // W
  "wait": ["等待"],
  "walk": ["走"],
  "wall": ["墙"],
  "want": ["想要"],
  "war": ["战争"],
  "watch": ["看", "手表"],
  "water": ["水"],
  "way": ["方法", "路"],
  "we": ["我们"],
  "weapon": ["武器"],
  "wear": ["穿"],
  "weather": ["天气"],
  "week": ["周"],
  "weight": ["重量"],
  "well": ["好"],
  "west": ["西方"],
  "what": ["什么"],
  "when": ["当…时"],
  "where": ["哪里"],
  "whether": ["是否"],
  "which": ["哪个"],
  "while": ["当…时", "虽然"],
  "white": ["白色的"],
  "who": ["谁"],
  "whole": ["整个"],
  "why": ["为什么"],
  "wide": ["宽的"],
  "wife": ["妻子"],
  "will": ["将"],
  "win": ["赢"],
  "wind": ["风"],
  "window": ["窗户"],
  "wish": ["希望"],
  "with": ["和", "用"],
  "without": ["没有"],
  "woman": ["女人"],
  "wonder": ["想知道"],
  "word": ["单词"],
  "work": ["工作"],
  "world": ["世界"],
  "worry": ["担心"],
  "would": ["将"],
  "write": ["写"],
  "wrong": ["错误的"],
  // Y
  "year": ["年"],
  "yes": ["是"],
  "yet": ["然而", "还"],
  "you": ["你"],
  "young": ["年轻的"],
};

/**
 * Check if a word is a common word being used with an uncommon meaning.
 * Returns true if the word is in the common word list AND the definition
 * doesn't match any of the common meanings.
 */
export function isCommonWordWithUncommonMeaning(
  word: string,
  definition: string
): boolean {
  const lowerWord = word.toLowerCase();
  const commonMeanings = COMMON_WORDS[lowerWord];

  if (!commonMeanings) return false;
  if (!definition) return false;

  // Check if any common meaning keyword appears in the definition
  const hasCommonMeaning = commonMeanings.some((meaning) =>
    definition.includes(meaning)
  );

  // If none of the common meanings match, it's a 熟词僻义
  return !hasCommonMeaning;
}
